apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helm-snowflake-poc.fullname" . }}
  labels:
    app: {{ template "helm-snowflake-poc.name" . }}
    chart: {{ template "helm-snowflake-poc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "helm-snowflake-poc.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm-snowflake-poc.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: SNOWFLAKE_DSN
              valueFrom:
                secretKeyRef:
                  name: snowflakeconn
                  key: SNOWFLAKE_DSN
            - name: SNOWFLAKE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: snowflakeconn
                  key: SNOWFLAKE_DATABASE
            - name: SNOWFLAKE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: snowflakeconn
                  key: SNOWFLAKE_SCHEMA
            - name: SNOWFLAKE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: snowflakeconn
                  key: SNOWFLAKE_USERNAME
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snowflakeconn
                  key: SNOWFLAKE_PASSWORD
          ports:
            - name: http
              containerPort: 4080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
