apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snowflake-poc-root
spec:
  destination:
    namespace: snowflake-poc
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/apps
    repoURL: 'https://github.com/kublr/snowflake-poc'
    targetRevision: main
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
